name: kelp
channels:
  - conda-forge
dependencies:
  - python==3.11
  - pip
  - pip:
    - rioxarray
    - pystac-client
    - odc-stac
    - geoapis
    - python-dotenv
    - netcdf4
    - mapclassify # for geopandas.explore
    - folium # for geopandas.explore
    - matplotlib # for geopandas.explore
    - ipykernel
    - streamlit
    - "dask[distributed]" --upgrade
    - planetary_computer
    - streamlit-folium 
    - plotly_express
    - sesaborn
